### ISSUE TITLE
Does not work with systemd service unit

### ISSUE THREAD

**Issue by lichtscheu** [sim642/whatpulse#9]
Hi,

i want to automatically start whatpulsed, so i created an systemd service unit, everything seems fine and "starts" without error, but systemd status says it is inactive (dead), there is no whatpulsed process running, no .pid file created and no data gets pushed.

my whatpulsed.service file:

```
[Unit]
Description=mouse and keyboard tracker
Documentation=https://github.com/sim642/whatpulse

[Service]
ExecStart=/usr/bin/whatpulsed
WorkingDirectory=/usr/share/whatpulse

[Install]
WantedBy=default.target
```

Anyone tried this before? Is there anything wrong with my unit? Or does whatpulsed not support service units?

**Comment by sim642** [comment]
I haven't tried this myself but my suspicion is that it has something to do with the daemon nature of whatpulsed not being perfect: its configuration and logging rely on a writable working directory (`whatpulsed.json`, `stdout.log`, `stderr.log`). Maybe the issue has something to do with that. Another guess would be something related to how whatpulsed tries to daemonize itself not working via systemd.

**Comment by lichtscheu** [comment]
With the Service - WorkingDirectory Path, the `whatpulsed.json` seems to work, i had to change file permissions for the` stdout.log`, tomorrow i'll change permissions for the `stderr.log`, eventually this gives some errors. Would be really nice if it would be supported to use whatpulsed with systemd!

Unfortunately i'm not a linux/systemd pro, but if you have something i can test, i will =)

**Comment by eevee** [comment]
I suspect systemd expects the job to _not_ daemonize itself (since half the point of systemd is to daemonize things) — the typical double-fork means the original process cleanly exits of its own accord, and that's basically what systemd is reporting.  Probably just need a command-line arg to run in the foreground.

**Comment by lichtscheu** [comment]
lol.. my account on whatpulse got suspended... i think its time to move on and stop using tools like whatpulse -.-
